#pragma once
#include <Windows.h>

namespace EZ {
	namespace Log {
		void ErrorFromHR(HRESULT hr);
		void ErrorFromCode(DWORD errorCode);
		void Error(LPCWSTR errorMessage);
		void WarningFromHR(HRESULT hr);
		void WarningFromCode(DWORD errorCode);
		void Warning(LPCWSTR errorMessage);
	}
	enum class ConsoleColor : WORD {
		Black = 0,
		DarkRed = FOREGROUND_RED,
		DarkGreen = FOREGROUND_GREEN,
		DarkBlue = FOREGROUND_BLUE,
		DarkYellow = FOREGROUND_RED | FOREGROUND_GREEN,
		DarkCyan = FOREGROUND_GREEN | FOREGROUND_BLUE,
		DarkMagenta = FOREGROUND_RED | FOREGROUND_BLUE,
		DarkGrey = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
		Grey = FOREGROUND_INTENSITY,
		Red = FOREGROUND_RED | FOREGROUND_INTENSITY,
		Green = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
		Blue = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
		Yellow = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
		Cyan = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
		Magenta = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
		White = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
	};
}